#!/bin/bash
# Build jump_dir binaries


if [ "$1" == "test" ]; then
    # Run tests
    mkdir -p bin/test
    g++ src/jump_dir_core.cpp src/test.cpp -o bin/test/test_jump_dir
    bin/test/test_jump_dir
else
    g++ src/jump_dir_core.cpp src/get_key_list_main.cpp -o bin/get_key_list
    g++ src/jump_dir_core.cpp src/get_path_from_key_main.cpp -o bin/get_path_from_key
    g++ src/jump_dir_core.cpp src/key_exists_main.cpp -o bin/key_exists
    g++ src/jump_dir_core.cpp src/add_key_main.cpp -o bin/add_key
    g++ src/jump_dir_core.cpp src/remove_key_main.cpp -o bin/remove_key
    g++ src/jump_dir_core.cpp src/is_config_file_valid_main.cpp -o bin/is_config_file_valid
fi
