#!/bin/bash

FILES="src/jump_dir_core.cpp src/main/add_key_main.cpp src/main/get_key_list_main.cpp"
CHECKS='*,-modernize-use-trailing-return-type,-llvm-header-guard,-google-runtime-references,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-fuchsia-default-arguments-calls'
INCLUDE="-Isrc"

clang-tidy $FILES --checks=$CHECKS -header-filter=.* -- $INCLUDE
